package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"com.ecommerce/auth-service/internal/model"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type UserRepository struct {
	pool *pgxpool.Pool
}

func NewUserRepository(pool *pgxpool.Pool) *UserRepository {
	return &UserRepository{pool: pool}
}

func (r *UserRepository) InitSchema(ctx context.Context) error {
	if r.pool == nil {
		return nil
	}
	schema := `
	CREATE TABLE IF NOT EXISTS roles (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		role_name VARCHAR(60) NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS users (
		user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		full_name VARCHAR(100),
		user_name VARCHAR(100) NOT NULL UNIQUE,
		email VARCHAR(50) NOT NULL UNIQUE,
		gender VARCHAR(255) NOT NULL,
		phone_number VARCHAR(11) UNIQUE,
		image_url TEXT,
		keycloak_user_id VARCHAR(64) UNIQUE
	);

	CREATE TABLE IF NOT EXISTS user_role (
		user_id BIGINT NOT NULL,
		role_id BIGINT NOT NULL,
		CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
		CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
		CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
	);

	INSERT INTO roles (id, role_name) VALUES (1, 'USER') ON CONFLICT (id) DO NOTHING;
	INSERT INTO roles (id, role_name) VALUES (2, 'PM') ON CONFLICT (id) DO NOTHING;
	INSERT INTO roles (id, role_name) VALUES (3, 'ADMIN') ON CONFLICT (id) DO NOTHING;
	`
	_, err := r.pool.Exec(ctx, schema)
	return err
}

func (r *UserRepository) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	if r.pool == nil {
		return nil, errors.New("db not connected")
	}
	query := `
		SELECT user_id, COALESCE(full_name, ''), user_name, email, COALESCE(gender, ''), 
		       COALESCE(phone_number, ''), COALESCE(image_url, ''), COALESCE(keycloak_user_id, '')
		FROM users
		WHERE user_name = $1
	`
	var u model.User
	err := r.pool.QueryRow(ctx, query, username).Scan(
		&u.ID, &u.FullName, &u.Username, &u.Email, &u.Gender, &u.Phone, &u.Avatar, &u.KeycloakUserID,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	roles, _ := r.GetUserRoles(ctx, u.ID)
	u.Roles = roles
	return &u, nil
}

func (r *UserRepository) FindById(ctx context.Context, id int64) (*model.User, error) {
	if r.pool == nil {
		return nil, errors.New("db not connected")
	}
	query := `
		SELECT user_id, COALESCE(full_name, ''), user_name, email, COALESCE(gender, ''), 
		       COALESCE(phone_number, ''), COALESCE(image_url, ''), COALESCE(keycloak_user_id, '')
		FROM users
		WHERE user_id = $1
	`
	var u model.User
	err := r.pool.QueryRow(ctx, query, id).Scan(
		&u.ID, &u.FullName, &u.Username, &u.Email, &u.Gender, &u.Phone, &u.Avatar, &u.KeycloakUserID,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	roles, _ := r.GetUserRoles(ctx, u.ID)
	u.Roles = roles
	return &u, nil
}

func (r *UserRepository) FindAll(ctx context.Context, page, size int, sortBy, sortOrder string) ([]model.User, int64, error) {
	if r.pool == nil {
		return nil, 0, errors.New("db not connected")
	}

	col := "user_id"
	switch strings.ToLower(sortBy) {
	case "username", "user_name":
		col = "user_name"
	case "email":
		col = "email"
	case "fullname", "full_name":
		col = "full_name"
	default:
		col = "user_id"
	}

	order := "ASC"
	if strings.ToUpper(sortOrder) == "DESC" {
		order = "DESC"
	}

	var total int64
	err := r.pool.QueryRow(ctx, "SELECT COUNT(*) FROM users").Scan(&total)
	if err != nil {
		return nil, 0, err
	}

	offset := page * size
	query := fmt.Sprintf(`
		SELECT user_id, COALESCE(full_name, ''), user_name, email, COALESCE(gender, ''), 
		       COALESCE(phone_number, ''), COALESCE(image_url, ''), COALESCE(keycloak_user_id, '')
		FROM users
		ORDER BY %s %s
		LIMIT $1 OFFSET $2
	`, col, order)

	rows, err := r.pool.Query(ctx, query, size, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var users []model.User
	for rows.Next() {
		var u model.User
		if err := rows.Scan(&u.ID, &u.FullName, &u.Username, &u.Email, &u.Gender, &u.Phone, &u.Avatar, &u.KeycloakUserID); err != nil {
			return nil, 0, err
		}
		users = append(users, u)
	}

	return users, total, nil
}

func (r *UserRepository) Create(ctx context.Context, u *model.User, roleNames []string) (*model.User, error) {
	if r.pool == nil {
		return nil, errors.New("db not connected")
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	insertQuery := `
		INSERT INTO users (full_name, user_name, email, gender, phone_number, image_url, keycloak_user_id)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING user_id
	`
	err = tx.QueryRow(ctx, insertQuery, u.FullName, u.Username, u.Email, u.Gender, u.Phone, u.Avatar, u.KeycloakUserID).Scan(&u.ID)
	if err != nil {
		return nil, err
	}

	for _, rn := range roleNames {
		rnUpper := strings.ToUpper(strings.TrimSpace(rn))
		if rnUpper == "" {
			continue
		}
		_, err := tx.Exec(ctx, `
			INSERT INTO user_role (user_id, role_id)
			SELECT $1, id FROM roles WHERE role_name = $2
			ON CONFLICT DO NOTHING
		`, u.ID, rnUpper)
		if err != nil {
			return nil, err
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	return u, nil
}

func (r *UserRepository) Update(ctx context.Context, id int64, req model.UpdateUserRequest) (*model.User, error) {
	if r.pool == nil {
		return nil, errors.New("db not connected")
	}

	existing, err := r.FindById(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, nil
	}

	if req.FullName != nil {
		existing.FullName = *req.FullName
	}
	if req.Email != nil {
		existing.Email = *req.Email
	}
	if req.Gender != nil {
		existing.Gender = *req.Gender
	}
	if req.Phone != nil {
		existing.Phone = *req.Phone
	}
	if req.Avatar != nil {
		existing.Avatar = *req.Avatar
	}

	query := `
		UPDATE users
		SET full_name = $1, email = $2, gender = $3, phone_number = $4, image_url = $5
		WHERE user_id = $6
	`
	_, err = r.pool.Exec(ctx, query, existing.FullName, existing.Email, existing.Gender, existing.Phone, existing.Avatar, id)
	if err != nil {
		return nil, err
	}

	return existing, nil
}

func (r *UserRepository) Delete(ctx context.Context, id int64) error {
	if r.pool == nil {
		return errors.New("db not connected")
	}
	_, err := r.pool.Exec(ctx, "DELETE FROM users WHERE user_id = $1", id)
	return err
}

func (r *UserRepository) AssignRole(ctx context.Context, userId int64, roleName string) (bool, error) {
	if r.pool == nil {
		return false, errors.New("db not connected")
	}
	rn := strings.ToUpper(strings.TrimSpace(roleName))
	tag, err := r.pool.Exec(ctx, `
		INSERT INTO user_role (user_id, role_id)
		SELECT $1, id FROM roles WHERE role_name = $2
		ON CONFLICT DO NOTHING
	`, userId, rn)
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() > 0, nil
}

func (r *UserRepository) RevokeRole(ctx context.Context, userId int64, roleName string) (bool, error) {
	if r.pool == nil {
		return false, errors.New("db not connected")
	}
	rn := strings.ToUpper(strings.TrimSpace(roleName))
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM user_role
		WHERE user_id = $1 AND role_id IN (SELECT id FROM roles WHERE role_name = $2)
	`, userId, rn)
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() > 0, nil
}

func (r *UserRepository) GetUserRoles(ctx context.Context, userId int64) ([]string, error) {
	if r.pool == nil {
		return nil, errors.New("db not connected")
	}
	query := `
		SELECT r.role_name
		FROM roles r
		INNER JOIN user_role ur ON ur.role_id = r.id
		WHERE ur.user_id = $1
		ORDER BY r.id
	`
	rows, err := r.pool.Query(ctx, query, userId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var roles []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		roles = append(roles, role)
	}
	return roles, nil
}

func (r *UserRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	if r.pool == nil {
		return false, nil
	}
	var exists bool
	err := r.pool.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM users WHERE user_name = $1)", username).Scan(&exists)
	return exists, err
}

func (r *UserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	if r.pool == nil {
		return false, nil
	}
	var exists bool
	err := r.pool.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)", email).Scan(&exists)
	return exists, err
}

func (r *UserRepository) ExistsByPhone(ctx context.Context, phone string) (bool, error) {
	if r.pool == nil {
		return false, nil
	}
	var exists bool
	err := r.pool.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM users WHERE phone_number = $1)", phone).Scan(&exists)
	return exists, err
}
