package repository

import (
	"context"
	"database/sql"
	"errors"
	"strings"

	"com.ecommerce/auth-service/internal/model"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/fm"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	pgxdriver "github.com/stephenafamo/bob/drivers/pgx"
	"github.com/stephenafamo/scan"
)

type UserRepository struct {
	db pgxdriver.Pool
}

func NewUserRepository(pool *pgxpool.Pool) *UserRepository {
	return &UserRepository{db: pgxdriver.NewPool(pool)}
}

func (r *UserRepository) InitSchema(ctx context.Context) error {
	if r.db.Pool == nil {
		return nil
	}
	schema := `
	CREATE TABLE IF NOT EXISTS roles (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		role_name VARCHAR(60) NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS users (
		user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		full_name VARCHAR(100),
		user_name VARCHAR(100) NOT NULL UNIQUE,
		email VARCHAR(50) NOT NULL UNIQUE,
		gender VARCHAR(255) NOT NULL,
		phone_number VARCHAR(11) UNIQUE,
		image_url TEXT,
		keycloak_user_id VARCHAR(64) UNIQUE
	);

	CREATE TABLE IF NOT EXISTS user_role (
		user_id BIGINT NOT NULL,
		role_id BIGINT NOT NULL,
		CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
		CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
		CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
	);

	INSERT INTO roles (id, role_name) VALUES (1, 'USER') ON CONFLICT (id) DO NOTHING;
	INSERT INTO roles (id, role_name) VALUES (2, 'PM') ON CONFLICT (id) DO NOTHING;
	INSERT INTO roles (id, role_name) VALUES (3, 'ADMIN') ON CONFLICT (id) DO NOTHING;
	`
	_, err := r.db.Exec(ctx, schema)
	return err
}

type userRow struct {
	ID             int64  `db:"user_id"`
	FullName       string `db:"full_name"`
	Username       string `db:"user_name"`
	Email          string `db:"email"`
	Gender         string `db:"gender"`
	Phone          string `db:"phone_number"`
	Avatar         string `db:"image_url"`
	KeycloakUserID string `db:"keycloak_user_id"`
}

func (row userRow) toModel() *model.User {
	return &model.User{
		ID:             row.ID,
		FullName:       row.FullName,
		Username:       row.Username,
		Email:          row.Email,
		Gender:         row.Gender,
		Phone:          row.Phone,
		Avatar:         row.Avatar,
		KeycloakUserID: row.KeycloakUserID,
	}
}

func userColumns() []any {
	return []any{
		psql.Quote("user_id"),
		psql.F("COALESCE", psql.Quote("full_name"), psql.S(""))(fm.As("full_name")),
		psql.Quote("user_name"),
		psql.Quote("email"),
		psql.F("COALESCE", psql.Quote("gender"), psql.S(""))(fm.As("gender")),
		psql.F("COALESCE", psql.Quote("phone_number"), psql.S(""))(fm.As("phone_number")),
		psql.F("COALESCE", psql.Quote("image_url"), psql.S(""))(fm.As("image_url")),
		psql.F("COALESCE", psql.Quote("keycloak_user_id"), psql.S(""))(fm.As("keycloak_user_id")),
	}
}

func roleByNameQuery(roleName string) bob.BaseQuery[*dialect.SelectQuery] {
	return psql.Select(
		sm.Columns(psql.Quote("id")),
		sm.From("roles"),
		sm.Where(psql.Quote("role_name").EQ(psql.Arg(roleName))),
	)
}

func orderByMod(col string, order string) dialect.OrderBy[*dialect.SelectQuery] {
	mod := sm.OrderBy(psql.Quote(col))
	if order == "DESC" {
		return mod.Desc()
	}
	return mod.Asc()
}

func (r *UserRepository) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	if r.db.Pool == nil {
		return nil, errors.New("db not connected")
	}
	query := psql.Select(
		sm.Columns(userColumns()...),
		sm.From("users"),
		sm.Where(psql.Quote("user_name").EQ(psql.Arg(username))),
	)
	row, err := bob.One(ctx, r.db, query, scan.StructMapper[userRow]())
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	user := row.toModel()
	roles, _ := r.GetUserRoles(ctx, user.ID)
	user.Roles = roles
	return user, nil
}

func (r *UserRepository) FindById(ctx context.Context, id int64) (*model.User, error) {
	if r.db.Pool == nil {
		return nil, errors.New("db not connected")
	}
	query := psql.Select(
		sm.Columns(userColumns()...),
		sm.From("users"),
		sm.Where(psql.Quote("user_id").EQ(psql.Arg(id))),
	)
	row, err := bob.One(ctx, r.db, query, scan.StructMapper[userRow]())
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	user := row.toModel()
	roles, _ := r.GetUserRoles(ctx, user.ID)
	user.Roles = roles
	return user, nil
}

func (r *UserRepository) FindAll(ctx context.Context, page, size int, sortBy, sortOrder string) ([]model.User, int64, error) {
	if r.db.Pool == nil {
		return nil, 0, errors.New("db not connected")
	}

	col := "user_id"
	switch strings.ToLower(sortBy) {
	case "username", "user_name":
		col = "user_name"
	case "email":
		col = "email"
	case "fullname", "full_name":
		col = "full_name"
	default:
		col = "user_id"
	}

	order := "ASC"
	if strings.ToUpper(sortOrder) == "DESC" {
		order = "DESC"
	}

	countQuery := psql.Select(
		sm.Columns("COUNT(*)"),
		sm.From("users"),
	)
	total, err := bob.One(ctx, r.db, countQuery, scan.SingleColumnMapper[int64])
	if err != nil {
		return nil, 0, err
	}

	query := psql.Select(
		sm.Columns(userColumns()...),
		sm.From("users"),
		orderByMod(col, order),
		sm.Limit(size),
		sm.Offset(page*size),
	)
	rows, err := bob.All(ctx, r.db, query, scan.StructMapper[userRow]())
	if err != nil {
		return nil, 0, err
	}

	users := make([]model.User, 0, len(rows))
	for _, row := range rows {
		users = append(users, *row.toModel())
	}
	return users, total, nil
}

func (r *UserRepository) Create(ctx context.Context, u *model.User, roleNames []string) (*model.User, error) {
	if r.db.Pool == nil {
		return nil, errors.New("db not connected")
	}

	tx, err := r.db.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	insertQuery := psql.Insert(
		im.Into("users", "full_name", "user_name", "email", "gender", "phone_number", "image_url", "keycloak_user_id"),
		im.Values(
			psql.Arg(u.FullName),
			psql.Arg(u.Username),
			psql.Arg(u.Email),
			psql.Arg(u.Gender),
			psql.Arg(u.Phone),
			psql.Arg(u.Avatar),
			psql.Arg(u.KeycloakUserID),
		),
		im.Returning("user_id"),
	)
	u.ID, err = bob.One(ctx, tx, insertQuery, scan.SingleColumnMapper[int64])
	if err != nil {
		return nil, err
	}

	for _, rn := range roleNames {
		rnUpper := strings.ToUpper(strings.TrimSpace(rn))
		if rnUpper == "" {
			continue
		}
		roleQuery := psql.Insert(
			im.Into("user_role", "user_id", "role_id"),
			im.Query(psql.Select(
				sm.Columns(psql.Arg(u.ID), psql.Quote("id")),
				sm.From("roles"),
				sm.Where(psql.Quote("role_name").EQ(psql.Arg(rnUpper))),
			)),
			im.OnConflict().DoNothing(),
		)
		if _, err := bob.Exec(ctx, tx, roleQuery); err != nil {
			return nil, err
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	return u, nil
}

func (r *UserRepository) Update(ctx context.Context, id int64, req model.UpdateUserRequest) (*model.User, error) {
	if r.db.Pool == nil {
		return nil, errors.New("db not connected")
	}

	existing, err := r.FindById(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, nil
	}

	if req.FullName != nil {
		existing.FullName = *req.FullName
	}
	if req.Email != nil {
		existing.Email = *req.Email
	}
	if req.Gender != nil {
		existing.Gender = *req.Gender
	}
	if req.Phone != nil {
		existing.Phone = *req.Phone
	}
	if req.Avatar != nil {
		existing.Avatar = *req.Avatar
	}

	query := psql.Update(
		um.Table("users"),
		um.Set(
			psql.Quote("full_name").EQ(psql.Arg(existing.FullName)),
			psql.Quote("email").EQ(psql.Arg(existing.Email)),
			psql.Quote("gender").EQ(psql.Arg(existing.Gender)),
			psql.Quote("phone_number").EQ(psql.Arg(existing.Phone)),
			psql.Quote("image_url").EQ(psql.Arg(existing.Avatar)),
		),
		um.Where(psql.Quote("user_id").EQ(psql.Arg(id))),
	)
	if _, err = bob.Exec(ctx, r.db, query); err != nil {
		return nil, err
	}

	return existing, nil
}

func (r *UserRepository) Delete(ctx context.Context, id int64) error {
	if r.db.Pool == nil {
		return errors.New("db not connected")
	}
	query := psql.Delete(
		dm.From("users"),
		dm.Where(psql.Quote("user_id").EQ(psql.Arg(id))),
	)
	_, err := bob.Exec(ctx, r.db, query)
	return err
}

func (r *UserRepository) AssignRole(ctx context.Context, userId int64, roleName string) (bool, error) {
	if r.db.Pool == nil {
		return false, errors.New("db not connected")
	}
	rn := strings.ToUpper(strings.TrimSpace(roleName))
	query := psql.Insert(
		im.Into("user_role", "user_id", "role_id"),
		im.Query(psql.Select(
			sm.Columns(psql.Arg(userId), psql.Quote("id")),
			sm.From("roles"),
			sm.Where(psql.Quote("role_name").EQ(psql.Arg(rn))),
		)),
		im.OnConflict().DoNothing(),
	)
	result, err := bob.Exec(ctx, r.db, query)
	if err != nil {
		return false, err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	return affected > 0, nil
}

func (r *UserRepository) RevokeRole(ctx context.Context, userId int64, roleName string) (bool, error) {
	if r.db.Pool == nil {
		return false, errors.New("db not connected")
	}
	rn := strings.ToUpper(strings.TrimSpace(roleName))
	query := psql.Delete(
		dm.From("user_role"),
		dm.Where(psql.And(
			psql.Quote("user_id").EQ(psql.Arg(userId)),
			psql.Quote("role_id").In(roleByNameQuery(rn)),
		)),
	)
	result, err := bob.Exec(ctx, r.db, query)
	if err != nil {
		return false, err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	return affected > 0, nil
}

func (r *UserRepository) GetUserRoles(ctx context.Context, userId int64) ([]string, error) {
	if r.db.Pool == nil {
		return nil, errors.New("db not connected")
	}
	query := psql.Select(
		sm.Columns(psql.Quote("r", "role_name")),
		sm.From("roles r"),
		sm.InnerJoin("user_role ur").On(psql.Raw("ur.role_id = r.id")),
		sm.Where(psql.Quote("ur", "user_id").EQ(psql.Arg(userId))),
		sm.OrderBy(psql.Quote("r", "id")).Asc(),
	)
	return bob.All(ctx, r.db, query, scan.SingleColumnMapper[string])
}

func (r *UserRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	if r.db.Pool == nil {
		return false, nil
	}
	query := psql.Select(
		sm.Columns(psql.Exists(psql.Select(
			sm.Columns("1"),
			sm.From("users"),
			sm.Where(psql.Quote("user_name").EQ(psql.Arg(username))),
		))),
	)
	return bob.One(ctx, r.db, query, scan.SingleColumnMapper[bool])
}

func (r *UserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	if r.db.Pool == nil {
		return false, nil
	}
	query := psql.Select(
		sm.Columns(psql.Exists(psql.Select(
			sm.Columns("1"),
			sm.From("users"),
			sm.Where(psql.Quote("email").EQ(psql.Arg(email))),
		))),
	)
	return bob.One(ctx, r.db, query, scan.SingleColumnMapper[bool])
}

func (r *UserRepository) ExistsByPhone(ctx context.Context, phone string) (bool, error) {
	if r.db.Pool == nil {
		return false, nil
	}
	query := psql.Select(
		sm.Columns(psql.Exists(psql.Select(
			sm.Columns("1"),
			sm.From("users"),
			sm.Where(psql.Quote("phone_number").EQ(psql.Arg(phone))),
		))),
	)
	return bob.One(ctx, r.db, query, scan.SingleColumnMapper[bool])
}
